### ISSUE TITLE
Need a way to refresh the status bar

### ISSUE THREAD

**Issue by Randalphwa** [alexzshl/vscode-taskshere#1]
If you change whether a task is hidden or not (`"tasksHereDisplay": "hide"`) the status bar remains unchanged until you either switch directories, or close/reopen VS Code. Same problem if you enter/change the name.

If there is a command you can call to get VS Code to refresh the status bar, perhaps you could add a command to the Actions menu?

**Comment by alexzshl** [comment]
sorry, but it has been designed to refresh status bar when change configuration.Are you sure that your status bar has not changed when you save tasks.json?

**Comment by Randalphwa** [comment]
I didn't think about this when I first wrote the issue, but I use a symbolic link to tasks.json so that all projects share the same task list. I'm guessing that there is an issue with it being a link rather than an actual file that is causing the problem. That would be a problem on VS Code's end, so nothing you can do about it.

**Comment by alexzshl** [comment]
Maybe you can try hard links. After my tests, it works.
